KBBMVAXR ;CLD/JPW - VAX REGISTRY CORE ROUTINES;7 JUL 2015
;;0.01;VAXR;***;7 JUL 2015;Build 0
 L (^KBBMVAXR):30
 I $TEST D
 . S ^KBBMVAXR("IEN")=0,^KBBMVAXR("RECORDS")=""
 . L 
 E  D 
 . D ERROR("COULD NOT LOCK IEN")
 Q
 ;;
INCRIEN()
 N IEN S IEN=0 L (^KBBMVAXR("IEN")):30
 I $TEST D
 . S ^KBBMVAXR("IEN")=^KBBMVAXR("IEN")+1,IEN=^KBBMVAXR("IEN") 
 . L
 E  D 
 . D ERROR("COULD NOT LOCK IEN")
 Q IEN
 ;;
INSERT(RECORD)
 N IEN S IEN=$$INCRIEN() L (^KBBMVAXR("RECORDS",IEN)):30
 I $TEST D
 . M ^KBBMVAXR("RECORDS",IEN)=RECORD
 . L
 E  D
 . D ERROR("COULD NOT INSERT RECORD "_IEN)
 D INDEX(IEN,.RECORD) 
 Q IEN
 ;;
DELETE(IEN)
 L (^KBBMVAXR("RECORDS",IEN)):30
 I $TEST D
 . D UNINDEX(IEN)
 . K ^KBBMVAXR("RECORDS",IEN)
 . L
 E  D
 . D ERROR("COULD NOT DELETE RECORD "_IEN)
 Q IEN
 ;;
UPDATE(IEN,RECORD)
 L (^KBBMVAXR("RECORDS",IEN)):30
 I $TEST D
 . M ^KBBMVAXR("RECORDS",IEN)=RECORD
 . L
 E  D
 . D ERROR("COULD NOT UPDATE RECORD "_IEN)
 Q IEN
 ;;
RETRIEVE(IEN,RECORD)
 M RECORD=^KBBMVAXR("RECORDS",IEN)
 Q IEN
 ;;
INDEX(IEN,RECORD)
 L (^KBBMVAXI):30 
 I $TEST D
 . S ^KBBMVAXI("RECLIST",IEN)="",^KBBMVAXI("INDEX",RECORD("INDEX"),IEN)=""
 . L
 E  D
 . D ERROR("COULD NOT UPDATE INDEX FOR "_IEN)
 Q
 ;;
UNINDEX(IEN)
 L (^KBBMVAXI):30
 I $TEST D
 . K ^KBBMVAXI("RECLIST",IEN)
 . K ^KBBMVAXI("INDEX",RECORD("INDEX"))
 . L
 E  D
 . D ERROR("COULD NOT REMOVE INDEX FOR "_IEN)
 Q
 ;;
ERROR(MESG)
 W "VAXR ERROR:  ",MESG,! H
 ;;