KBBMVTUI ;CLD/JPW - VAX REGISTRY TUI;7 JUL 2015
;;0.01;VAXR;***;7 JUL 2015;Build 0
 D MTUI^MTUI("VAXREGISTRY","VAX-11 REGISTRY")
 D INIT^MTUI
PRIMARY
 N MA
 S MA("TITLE")="MAIN MENU"
 S MA("ITEMS","A)  VIEW REGISTRY")="D VIEWREG^KBBMVTUI"
 S MA("ITEMS","B)  ADD SYSTEM")="D ADDSYS^KBBMVTUI"
 S MA("ITEMS","QUIT")="D QUITREG^KBBMVTUI"
 D GO^MTUIMENU(.MA)
 G PRIMARY
 Q
 ;;
VIEWREG
 N FILE S FILE="VAXREGIS.TXT" O FILE
 D VIEW^MTUIFILE(FILE,"VAX REGISTRY REPORT")
 C FILE
 Q
 ;;
ADDSYS
 N MA,RECORD,MODEL,OPERATIONAL,NETWORKED
 S MA("TITLE")="SELECT SYSTEM MODEL"
 S MA("ITEMS","00)  VAX-11/780")="S MODEL=""VAX-11/780"""
 S MA("ITEMS","01)  VAX-11/750")="S MODEL=""VAX-11/750"""
 S MA("ITEMS","02)  VAX-11/751")="S MODEL=""VAX-11/751"""
 S MA("ITEMS","03)  VAX-11/730")="S MODEL=""VAX-11/730"""
 S MA("ITEMS","04)  VAX-11/782")="S MODEL=""VAX-11/782"""
 S MA("ITEMS","05)  VAX-11/784")="S MODEL=""VAX-11/784"""
 S MA("ITEMS","06)  VAX-11/785")="S MODEL=""VAX-11/785"""
 S MA("ITEMS","07)  VAX-11/787")="S MODEL=""VAX-11/787"""
 S MA("ITEMS","08)  VAX-11/788")="S MODEL=""VAX-11/788"""
 S MA("ITEMS","09)  VAX-11/725")="S MODEL=""VAX-11/725"""
 S MA("ITEMS","10)  VAX 8600")="S MODEL=""VAX 8600"""
 S MA("ITEMS","11)  VAX 8650")="S MODEL=""VAX 8650"""
 D GO^MTUIMENU(.MA)
 S (RECORD("INDEX"),RECORD("MODEL"))=MODEL
 K MA
 S MA("TITLE")="OPERATIONAL STATUS"
 S MA("ITEMS","OPERATIONAL")="S OPERATIONAL=""OPERATIONAL"""
 S MA("ITEMS","NON-OPERATIONAL")="S OPERATIONAL=""NON-OPERATIONAL"""
 S MA("ITEMS","UNKNOWN")="S OPERATIONAL=""UNKNOWN"""
 D GO^MTUIMENU(.MA)
 S RECORD("OPERATIONAL")=OPERATIONAL
 I OPERATIONAL>0 D
 . K MA
 . S MA("TITLE")="NETWORK ACCESSIBILITY"
 . S MA("ITEMS","NON-NETWORKED")="S NETWORKED=""NON-NETWORKED"""
 . S MA("ITEMS","NETWORKED; NO PUBLIC ACCESS")="S NETWORKED=""PRIVATE ONLY"""
 . S MA("ITEMS","NETWORKED; PUBLIC ACCESS AVAILABLE")="S NETWORKED=""PUBLIC"""
 . D GO^MTUIMENU(.MA)
 E  D
 . S NETWORKED="N/A"
 S RECORD("NETWORKED")=NETWORKED
 I OPERATIONAL>0 D
 . K MA
 . S MA("TITLE")="OPERATING SYSTEM"
 . S MA("ITEMS","VAX/VMS")="S OS=""VAX/VMS"""
 . S MA("ITEMS","ULTRIX")="S OS=""ULTRIX"""
 . S MA("ITEMS","4.xBSD (INCLUDING IFCTF QUASIJARUS)")="S OS=""4.xBSD"""
 . S MA("ITEMS","NETBSD")="S OS=""NETBSD"""
 . S MA("ITEMS","UNLISTED/OTHER OR NO OPERATING SYSTEM")="S OS=""OTHER"""
 . D GO^MTUIMENU(.MA)
 E  D
 . S OS="N/A"
 S RECORD("OS")=OS
 N FA
 S FA("TITLE")="OWNER INFORMATION"
 S FA("ITEMS",1,"NAME")="NAME"
 S FA("ITEMS",1,"LABEL")="OWNER NAME:"
 S FA("ITEMS",1,"LABEL","TOP")=5
 S FA("ITEMS",1,"LABEL","LEFT")=2
 S FA("ITEMS",1,"FIELD","TOP")=6
 S FA("ITEMS",1,"FIELD","LEFT")=2
 S FA("ITEMS",1,"FIELD","MAXLENGTH")=20
 S FA("ITEMS",1,"FIELD","REQUIRED")=1
 S FA("ITEMS",2,"NAME")="EMAIL"
 S FA("ITEMS",2,"LABEL")="OWNER ELECTRONIC MAIL ADDRESS:"
 S FA("ITEMS",2,"LABEL","TOP")=8
 S FA("ITEMS",2,"LABEL","LEFT")=2
 S FA("ITEMS",2,"FIELD","TOP")=9
 S FA("ITEMS",2,"FIELD","LEFT")=2
 S FA("ITEMS",2,"FIELD","MAXLENGTH")=40
 S FA("ITEMS",2,"FIELD","REQUIRED")=1
 S FA("ITEMS",3,"NAME")="IP"
 S FA("ITEMS",3,"LABEL")="IPV4 ADDRESS:"
 S FA("ITEMS",3,"LABEL","TOP")=11
 S FA("ITEMS",3,"LABEL","LEFT")=2
 S FA("ITEMS",3,"FIELD","TOP")=12
 S FA("ITEMS",3,"FIELD","LEFT")=2
 S FA("ITEMS",3,"FIELD","MAXLENGTH")=15
 S FA("ITEMS",3,"FIELD","REQUIRED")=0
 S FA("ITEMS",4,"NAME")="BOOTDRIVE"
 S FA("ITEMS",4,"LABEL")="BOOT DRIVE MODEL (E.G. RM05):"
 S FA("ITEMS",4,"LABEL","TOP")=14
 S FA("ITEMS",4,"LABEL","LEFT")=2
 S FA("ITEMS",4,"FIELD","TOP")=15
 S FA("ITEMS",4,"FIELD","LEFT")=2
 S FA("ITEMS",4,"FIELD","MAXLENGTH")=6
 S FA("ITEMS",4,"FIELD","REQUIRED")=0
 S FA("ITEMS",5,"NAME")="COUNTRY"
 S FA("ITEMS",5,"LABEL")="COUNTRY CODE OF LOCATION:"
 S FA("ITEMS",5,"LABEL","TOP")=17
 S FA("ITEMS",5,"LABEL","LEFT")=2
 S FA("ITEMS",5,"FIELD","TOP")=18
 S FA("ITEMS",5,"FIELD","LEFT")=2
 S FA("ITEMS",5,"FIELD","MAXLENGTH")=3
 S FA("ITEMS",5,"FIELD","REQUIRED")=1
 S FA("ITEMS",6,"NAME")="STATE"
 S FA("ITEMS",6,"LABEL")="STATE/PROVINCE/REGION OF LOCATION:"
 S FA("ITEMS",6,"LABEL","TOP")=20
 S FA("ITEMS",6,"LABEL","LEFT")=2
 S FA("ITEMS",6,"FIELD","TOP")=21
 S FA("ITEMS",6,"FIELD","LEFT")=2
 S FA("ITEMS",6,"FIELD","MAXLENGTH")=30
 S FA("ITEMS",6,"FIELD","REQUIRED")=1
 D GO^MTUIFORM(.FA)
 G:CANFLG=1 CNADDSYS
 S RECORD("OWNERNAME")=$$GETEXTVAL^MTUIFORM(.FA,"NAME")
 S RECORD("EMAIL")=$$GETEXTVAL^MTUIFORM(.FA,"EMAIL")
 S RECORD("IP")=$$GETEXTVAL^MTUIFORM(.FA,"IP")
 S RECORD("BOOTDRIVE")=$$GETEXTVAL^MTUIFORM(.FA,"BOOTDRIVE")
 S RECORD("COUNTRY")=$$GETEXTVAL^MTUIFORM(.FA,"COUNTRY")
 S RECORD("STATE")=$$GETEXTVAL^MTUIFORM(.FA,"STATE")
 N IEN S IEN=$$INSERT^KBBMVAXR(.RECORD)
 D MSGBOX^MTUI("SYSTEM ENTERED AS IEN "_IEN,"","VAX-11 REGISTRY") 
 J GENREPT^KBBMVTUI
 Q
CNADDSYS
 D MSGBOX^MTUI("SYSTEM ENTRY CANCELED ON USER REQUEST","","VAX-11 REGISTRY")
 Q
 ;;
QUITREG
 S RESP=$$CONFIRM^MTUI("REALLY QUIT?")
 I RESP="Y" D
 . D RESET^MTUIUTIL
 . HALT
 Q
 ;;
GENREPT
 N FILE S FILE="VAXREGIS.TXT" O FILE:NEWVERSION
 U FILE
 N IEN,RECORD,I,RC S IEN="",RC=0
 N CO 
 S CO(1)=1,C0(2)=CO(1)+20,CO(2)=CO(1)+20,CO(3)=CO(2)+20,CO(3)=CO(2)+20
 S CO(4)=CO(3)+20,CO(5)=CO(4)+20,CO(6)=CO(5)+20
 S CO(7)=CO(6)+30,CO(8)=CO(7)+20,CO(9)=CO(8)+20,CO(10)=CO(9)+20
 F I=1:1:CO(10)+20 W "-"
 W !
 W "VAX-11 REGISTRY - ",$ZDATE($H)," BATCH ID = ",$J," HOROLOG = ",$H,!
 F I=1:1:CO(10)+20 W "-"
 W !
 W "MODEL",?CO(2),"CONDITION",?CO(3),"NETWORK",?CO(4),"OS",?CO(5),"OWNER",?CO(6),"EMAIL",?CO(7),"IPV4 ADDR",?CO(8),"BOOT DRIVE",?CO(9),"COUNTRY",?CO(10),"STATE/REGION",!
 F I=1:1:CO(10)+20 W "-"
 W !
 F  S IEN=$O(^KBBMVAXR("RECORDS",IEN)) Q:IEN=""  D
 . M RECORD=^KBBMVAXR("RECORDS",IEN)
 . W RECORD("MODEL")
 . W ?CO(2),$G(RECORD("OPERATIONAL"))
 . W ?CO(3),$G(RECORD("NETWORKED"))
 . W ?CO(4),$G(RECORD("OS"))
 . W ?CO(5),$G(RECORD("OWNERNAME"))
 . W ?CO(6),$G(RECORD("EMAIL"))
 . W ?CO(7),$G(RECORD("IP"))
 . W ?CO(8),$G(RECORD("BOOTDRIVE"))
 . W ?CO(9),$G(RECORD("COUNTRY"))
 . W ?CO(10),$G(RECORD("STATE")),!
 . K RECORD
 . S RC=RC+1
 F I=1:1:CO(10)+20 W "-"
 W !,RC," RECORDS IN REGISTRY"
 U $P
 C FILE
 Q